# Generated by Django 3.0.8 on 2020-07-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cls_view_details',
            old_name='view_details',
            new_name='name',
        ),
    ]
